name: build rpm package

on:
  workflow_dispatch:
    branches:
    - default

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: build rpm package
      uses: kentik/pkg@v1.0.0-rc8
      with:
        name: dropbear
        version: 2022.88
        arch: aarch64
        format: rpm
        package: rpm/dropbear.spec

# You may pin to the exact commit or the version.
# uses: kentik/pkg@741cfff0b19710dc6016a7a4d60c8ff2607068ff
# https://github.com/marketplace/actions/build-linux-packages
