name: rpmbuild for centos8

on:
  workflow_dispatch:
    branches:
    - default

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build RPM
      uses: biohuns/rpmbuild-centos8-action@v1.0.0
